# Build settings
gems:
  - jemoji
  - jekyll-paginate

plugins:
  - jekyll-spaceship

# Site settings
title: "Ero"
description: > # this means to ignore newlines until "email:"
   A collection of some of my thoughts

email: hello@ayokan.me
logo: "/assets/images/ero_logo.png"
float_logo: true # true, false (default)

# permalink settings -> can be overridden in post fron-matter
collections:
  posts:
    output: true
    permalink: /:title

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'ayokanme'
author: 'Muizz Matemilola'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://ayokan.me"
baseurl: ""
twitter_handle: '@ayokanme'


#google_analytics: UA-XXXXX-X

social:
  - icon:	twitter
    url:	https://twitter.com/ayokanme
    desc: Follow me on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/ayokanme
    desc:	Check out my work on GitHub
    share_url:
    share_title:
    share_link:
    
  - icon:	handshake-o
    url:	https://collab.ayokan.me
    desc: Collaborate with me on PolyWork
    share_url:
    share_title:
    share_link:

  - icon:	file-text-o
    url:	https://resume.ayokan.me
    desc:	My resume
    share_url:
    share_title:
    share_link:
    
  - icon:	address-card-o
    url:	https://ayokan.me/about
    desc:	About me
    share_url:
    share_title:
    share_link:    
